# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04596440c7205d2064e2e8c3f7e3065173d2274efc8556f2fb79e0998526d201afb87c33f51196c18af71f9e49bd3947406c49698f6b6fdf898cd3009e035ed5

test:
  secret_key_base: 5e2a900b5a474563fb6a0aa3e8a2a9005b9bbb495b4358ea6802c59c84672f0e3c368ea17572673f7cb417c885a101f787e8d60f1ce0a04680c6918f47171917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
